[env:QITAS]
; upgrade platform when I2CDevlib is updated
platform = espressif8266
framework = arduino
board = esp12e

lib_deps =
    Streaming
    I2Cdevlib-MPU6050

board_build.flash_mode = dio
upload_speed = 921600
monitor_baud = 115200
;monitor_baud = 9600
